import Head from 'next/head';

export default function Layout ({children}) {
    return (<>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <div className="header-container">
      <div className="header-title-image-container">
        <a href="/" className="title-image"><img src="/vercel.svg" alt="Vercel Logo" /></a>
      </div>
      <div className="header-link-container">
        <a href="/future-events"><h2>Future Events</h2></a>
        <a href="/sermon-archive"><h2>Sermon Archive</h2></a>
        <a href="/teachings"><h2>Teachings</h2></a>
      </div>
    </div>
    {children}
    </>)
}